import React from "react";
import { GateType } from "@/src/libs/types";

/**
 * SVG path definitions for primitive gate symbols.
 */
export const GATE_PATHS: Record<GateType, React.ReactNode> = {
  [GateType.AND]: (
    <>
      <path
        d="M20,10 L50,10 A20,20 0 0,1 50,50 L20,50 Z"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
      />
      <line
        x1="0"
        y1="20"
        x2="20"
        y2="20"
        stroke="currentColor"
        strokeWidth="2"
      />
      <line
        x1="0"
        y1="40"
        x2="20"
        y2="40"
        stroke="currentColor"
        strokeWidth="2"
      />
      <line
        x1="70"
        y1="30"
        x2="100"
        y2="30"
        stroke="currentColor"
        strokeWidth="2"
      />
    </>
  ),
  [GateType.OR]: (
    <>
      <path
        d="M20,10 Q40,10 70,30 Q40,50 20,50 Q30,30 20,10 Z"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
      />
      <line
        x1="0"
        y1="20"
        x2="25"
        y2="20"
        stroke="currentColor"
        strokeWidth="2"
      />
      <line
        x1="0"
        y1="40"
        x2="25"
        y2="40"
        stroke="currentColor"
        strokeWidth="2"
      />
      <line
        x1="70"
        y1="30"
        x2="100"
        y2="30"
        stroke="currentColor"
        strokeWidth="2"
      />
    </>
  ),
  [GateType.NOT]: (
    <>
      <path
        d="M30,15 L60,30 L30,45 Z"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
      />
      <circle
        cx="65"
        cy="30"
        r="5"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
      />
      <line
        x1="0"
        y1="30"
        x2="30"
        y2="30"
        stroke="currentColor"
        strokeWidth="2"
      />
      <line
        x1="70"
        y1="30"
        x2="100"
        y2="30"
        stroke="currentColor"
        strokeWidth="2"
      />
    </>
  ),
  [GateType.NAND]: (
    <>
      <path
        d="M20,10 L50,10 A20,20 0 0,1 50,50 L20,50 Z"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
      />
      <circle
        cx="75"
        cy="30"
        r="5"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
      />
      <line
        x1="0"
        y1="20"
        x2="20"
        y2="20"
        stroke="currentColor"
        strokeWidth="2"
      />
      <line
        x1="0"
        y1="40"
        x2="20"
        y2="40"
        stroke="currentColor"
        strokeWidth="2"
      />
      <line
        x1="80"
        y1="30"
        x2="100"
        y2="30"
        stroke="currentColor"
        strokeWidth="2"
      />
    </>
  ),
  [GateType.NOR]: (
    <>
      <path
        d="M20,10 Q40,10 70,30 Q40,50 20,50 Q30,30 20,10 Z"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
      />
      <circle
        cx="75"
        cy="30"
        r="5"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
      />
      <line
        x1="0"
        y1="20"
        x2="25"
        y2="20"
        stroke="currentColor"
        strokeWidth="2"
      />
      <line
        x1="0"
        y1="40"
        x2="25"
        y2="40"
        stroke="currentColor"
        strokeWidth="2"
      />
      <line
        x1="80"
        y1="30"
        x2="100"
        y2="30"
        stroke="currentColor"
        strokeWidth="2"
      />
    </>
  ),
  [GateType.XOR]: (
    <>
      <path
        d="M15,10 Q25,30 15,50"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
      />
      <path
        d="M25,10 Q45,10 75,30 Q45,50 25,50 Q35,30 25,10 Z"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
      />
      <line
        x1="0"
        y1="20"
        x2="22"
        y2="20"
        stroke="currentColor"
        strokeWidth="2"
      />
      <line
        x1="0"
        y1="40"
        x2="22"
        y2="40"
        stroke="currentColor"
        strokeWidth="2"
      />
      <line
        x1="75"
        y1="30"
        x2="100"
        y2="30"
        stroke="currentColor"
        strokeWidth="2"
      />
    </>
  ),
  [GateType.XNOR]: (
    <>
      <path
        d="M15,10 Q25,30 15,50"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
      />
      <path
        d="M25,10 Q45,10 75,30 Q45,50 25,50 Q35,30 25,10 Z"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
      />
      <circle
        cx="80"
        cy="30"
        r="5"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
      />
      <line
        x1="0"
        y1="20"
        x2="22"
        y2="20"
        stroke="currentColor"
        strokeWidth="2"
      />
      <line
        x1="0"
        y1="40"
        x2="22"
        y2="40"
        stroke="currentColor"
        strokeWidth="2"
      />
      <line
        x1="85"
        y1="30"
        x2="100"
        y2="30"
        stroke="currentColor"
        strokeWidth="2"
      />
    </>
  ),
};
