import {
  GateType,
  LogicValue,
  GateDefinition,
  ICDefinition,
  Pin,
} from "@/src/libs/types";

export const GATES: Record<GateType, GateDefinition> = {
  [GateType.AND]: {
    type: GateType.AND,
    name: "AND Gate",
    mnemonic: "All must agree",
    description: "Outputs HIGH only if all inputs are HIGH.",
    expression: "Y = A · B",
    truthTable: [
      { inputs: [LogicValue.LOW, LogicValue.LOW], output: LogicValue.LOW },
      { inputs: [LogicValue.LOW, LogicValue.HIGH], output: LogicValue.LOW },
      { inputs: [LogicValue.HIGH, LogicValue.LOW], output: LogicValue.LOW },
      { inputs: [LogicValue.HIGH, LogicValue.HIGH], output: LogicValue.HIGH },
    ],
  },
  [GateType.OR]: {
    type: GateType.OR,
    name: "OR Gate",
    mnemonic: "One is enough",
    description: "Outputs HIGH if at least one input is HIGH.",
    expression: "Y = A + B",
    truthTable: [
      { inputs: [LogicValue.LOW, LogicValue.LOW], output: LogicValue.LOW },
      { inputs: [LogicValue.LOW, LogicValue.HIGH], output: LogicValue.HIGH },
      { inputs: [LogicValue.HIGH, LogicValue.LOW], output: LogicValue.HIGH },
      { inputs: [LogicValue.HIGH, LogicValue.HIGH], output: LogicValue.HIGH },
    ],
  },
  [GateType.NOT]: {
    type: GateType.NOT,
    name: "NOT Gate (Inverter)",
    mnemonic: "The opposite",
    description: "Inverts the input signal.",
    expression: "Y = ¬A",
    truthTable: [
      { inputs: [LogicValue.LOW], output: LogicValue.HIGH },
      { inputs: [LogicValue.HIGH], output: LogicValue.LOW },
    ],
  },
  [GateType.NAND]: {
    type: GateType.NAND,
    name: "NAND Gate",
    mnemonic: "Not AND",
    description: "Outputs LOW only if all inputs are HIGH.",
    expression: "Y = ¬(A · B)",
    truthTable: [
      { inputs: [LogicValue.LOW, LogicValue.LOW], output: LogicValue.HIGH },
      { inputs: [LogicValue.LOW, LogicValue.HIGH], output: LogicValue.HIGH },
      { inputs: [LogicValue.HIGH, LogicValue.LOW], output: LogicValue.HIGH },
      { inputs: [LogicValue.HIGH, LogicValue.HIGH], output: LogicValue.LOW },
    ],
  },
  [GateType.NOR]: {
    type: GateType.NOR,
    name: "NOR Gate",
    mnemonic: "Not OR",
    description: "Outputs HIGH only if all inputs are LOW.",
    expression: "Y = ¬(A + B)",
    truthTable: [
      { inputs: [LogicValue.LOW, LogicValue.LOW], output: LogicValue.HIGH },
      { inputs: [LogicValue.LOW, LogicValue.HIGH], output: LogicValue.LOW },
      { inputs: [LogicValue.HIGH, LogicValue.LOW], output: LogicValue.LOW },
      { inputs: [LogicValue.HIGH, LogicValue.HIGH], output: LogicValue.LOW },
    ],
  },
  [GateType.XOR]: {
    type: GateType.XOR,
    name: "XOR Gate",
    mnemonic: "One but not both",
    description: "Outputs HIGH if exactly one input is HIGH.",
    expression: "Y = A ⊕ B",
    truthTable: [
      { inputs: [LogicValue.LOW, LogicValue.LOW], output: LogicValue.LOW },
      { inputs: [LogicValue.LOW, LogicValue.HIGH], output: LogicValue.HIGH },
      { inputs: [LogicValue.HIGH, LogicValue.LOW], output: LogicValue.HIGH },
      { inputs: [LogicValue.HIGH, LogicValue.HIGH], output: LogicValue.LOW },
    ],
  },
  [GateType.XNOR]: {
    type: GateType.XNOR,
    name: "XNOR Gate",
    mnemonic: "Both same",
    description: "Outputs HIGH if both inputs are the same.",
    expression: "Y = ¬(A ⊕ B)",
    truthTable: [
      { inputs: [LogicValue.LOW, LogicValue.LOW], output: LogicValue.HIGH },
      { inputs: [LogicValue.LOW, LogicValue.HIGH], output: LogicValue.LOW },
      { inputs: [LogicValue.HIGH, LogicValue.LOW], output: LogicValue.LOW },
      { inputs: [LogicValue.HIGH, LogicValue.HIGH], output: LogicValue.HIGH },
    ],
  },
};

const createQuadGatePinout = (gateName: string): Pin[] => [
  {
    id: "1",
    name: "1A",
    description: `Input A of gate 1`,
    type: "input",
    x: 0,
    y: 0,
  },
  {
    id: "2",
    name: "1B",
    description: `Input B of gate 1`,
    type: "input",
    x: 0,
    y: 0,
  },
  {
    id: "3",
    name: "1Y",
    description: `Output of gate 1`,
    type: "output",
    x: 0,
    y: 0,
  },
  {
    id: "4",
    name: "2A",
    description: `Input A of gate 2`,
    type: "input",
    x: 0,
    y: 0,
  },
  {
    id: "5",
    name: "2B",
    description: `Input B of gate 2`,
    type: "input",
    x: 0,
    y: 0,
  },
  {
    id: "6",
    name: "2Y",
    description: `Output of gate 2`,
    type: "output",
    x: 0,
    y: 0,
  },
  {
    id: "7",
    name: "GND",
    description: "Ground (0V)",
    type: "ground",
    x: 0,
    y: 0,
  },
  {
    id: "8",
    name: "3Y",
    description: `Output of gate 3`,
    type: "output",
    x: 0,
    y: 0,
  },
  {
    id: "9",
    name: "3A",
    description: `Input A of gate 3`,
    type: "input",
    x: 0,
    y: 0,
  },
  {
    id: "10",
    name: "3B",
    description: `Input B of gate 3`,
    type: "input",
    x: 0,
    y: 0,
  },
  {
    id: "11",
    name: "4Y",
    description: `Output of gate 4`,
    type: "output",
    x: 0,
    y: 0,
  },
  {
    id: "12",
    name: "4A",
    description: `Input A of gate 4`,
    type: "input",
    x: 0,
    y: 0,
  },
  {
    id: "13",
    name: "4B",
    description: `Input B of gate 4`,
    type: "input",
    x: 0,
    y: 0,
  },
  {
    id: "14",
    name: "VCC",
    description: "Positive Supply (+5V)",
    type: "power",
    x: 0,
    y: 0,
  },
];

export const ICS: Record<string, ICDefinition> = {
  "7400": {
    id: "7400",
    name: "7400 Quad 2-input NAND",
    description: "Contains four independent 2-input NAND gates.",
    pinout: createQuadGatePinout("NAND"),
    datasheetUrl: "https://www.ti.com/lit/ds/symlink/sn7400.pdf",
    diagramUrl: "/images/nand-gate.jpg"
  },
  "7402": {
    id: "7402",
    name: "7402 Quad 2-input NOR",
    description: "Contains four independent 2-input NOR gates.",
    pinout: [
      {
        id: "1",
        name: "1Y",
        description: "Output of gate 1",
        type: "output",
        x: 0,
        y: 0,
      },
      {
        id: "2",
        name: "1A",
        description: "Input A of gate 1",
        type: "input",
        x: 0,
        y: 0,
      },
      {
        id: "3",
        name: "1B",
        description: "Input B of gate 1",
        type: "input",
        x: 0,
        y: 0,
      },
      {
        id: "4",
        name: "2Y",
        description: "Output of gate 2",
        type: "output",
        x: 0,
        y: 0,
      },
      {
        id: "5",
        name: "2A",
        description: "Input A of gate 2",
        type: "input",
        x: 0,
        y: 0,
      },
      {
        id: "6",
        name: "2B",
        description: "Input B of gate 2",
        type: "input",
        x: 0,
        y: 0,
      },
      {
        id: "7",
        name: "GND",
        description: "Ground (0V)",
        type: "ground",
        x: 0,
        y: 0,
      },
      {
        id: "8",
        name: "3A",
        description: "Input A of gate 3",
        type: "input",
        x: 0,
        y: 0,
      },
      {
        id: "9",
        name: "3B",
        description: "Input B of gate 3",
        type: "input",
        x: 0,
        y: 0,
      },
      {
        id: "10",
        name: "3Y",
        description: "Output of gate 3",
        type: "output",
        x: 0,
        y: 0,
      },
      {
        id: "11",
        name: "4A",
        description: "Input A of gate 4",
        type: "input",
        x: 0,
        y: 0,
      },
      {
        id: "12",
        name: "4B",
        description: "Input B of gate 4",
        type: "input",
        x: 0,
        y: 0,
      },
      {
        id: "13",
        name: "4Y",
        description: "Output of gate 4",
        type: "output",
        x: 0,
        y: 0,
      },
      {
        id: "14",
        name: "VCC",
        description: "Positive Supply (+5V)",
        type: "power",
        x: 0,
        y: 0,
      },
    ],
    datasheetUrl: "https://www.ti.com/lit/ds/symlink/sn7402.pdf",
    diagramUrl: "/images/nor-gate.jpg"
  },
  "7404": {
    id: "7404",
    name: "7404 Hex Inverter",
    description: "Contains six independent NOT gates.",
    pinout: [
      {
        id: "1",
        name: "1A",
        description: "Input of inverter 1",
        type: "input",
        x: 0,
        y: 0,
      },
      {
        id: "2",
        name: "1Y",
        description: "Output of inverter 1",
        type: "output",
        x: 0,
        y: 0,
      },
      {
        id: "3",
        name: "2A",
        description: "Input of inverter 2",
        type: "input",
        x: 0,
        y: 0,
      },
      {
        id: "4",
        name: "2Y",
        description: "Output of inverter 2",
        type: "output",
        x: 0,
        y: 0,
      },
      {
        id: "5",
        name: "3A",
        description: "Input of inverter 3",
        type: "input",
        x: 0,
        y: 0,
      },
      {
        id: "6",
        name: "3Y",
        description: "Output of inverter 3",
        type: "output",
        x: 0,
        y: 0,
      },
      {
        id: "7",
        name: "GND",
        description: "Ground (0V)",
        type: "ground",
        x: 0,
        y: 0,
      },
      {
        id: "8",
        name: "4Y",
        description: "Output of inverter 4",
        type: "output",
        x: 0,
        y: 0,
      },
      {
        id: "9",
        name: "4A",
        description: "Input of inverter 4",
        type: "input",
        x: 0,
        y: 0,
      },
      {
        id: "10",
        name: "5Y",
        description: "Output of inverter 5",
        type: "output",
        x: 0,
        y: 0,
      },
      {
        id: "11",
        name: "5A",
        description: "Input of inverter 5",
        type: "input",
        x: 0,
        y: 0,
      },
      {
        id: "12",
        name: "6Y",
        description: "Output of inverter 6",
        type: "output",
        x: 0,
        y: 0,
      },
      {
        id: "13",
        name: "6A",
        description: "Input of inverter 6",
        type: "input",
        x: 0,
        y: 0,
      },
      {
        id: "14",
        name: "VCC",
        description: "Positive Supply (+5V)",
        type: "power",
        x: 0,
        y: 0,
      },
    ],
    datasheetUrl: "https://www.ti.com/lit/ds/symlink/sn7404.pdf",
    diagramUrl: "/images/not-gate.jpg"
  },
  "7408": {
    id: "7408",
    name: "7408 Quad 2-input AND",
    description: "Contains four independent 2-input AND gates.",
    pinout: createQuadGatePinout("AND"),
    datasheetUrl: "https://www.futurlec.com/74/IC7408.shtml",
    diagramUrl: "/images/and-gate.jpg"
  },
  "7432": {
    id: "7432",
    name: "7432 Quad 2-input OR",
    description: "Contains four independent 2-input OR gates.",
    pinout: createQuadGatePinout("OR"),
    datasheetUrl: "https://www.ti.com/lit/ds/symlink/sn7432.pdf",
    diagramUrl: "/images/or-gate.jpg"
  },
  "7486": {
    id: "7486",
    name: "7486 Quad 2-input XOR",
    description: "Contains four independent 2-input XOR gates.",
    pinout: createQuadGatePinout("XOR"),
    datasheetUrl: "https://www.ti.com/lit/ds/symlink/sn74hc86.pdf",
    diagramUrl: "/images/xor-gate.jpg"
  },
  "74266": {
    id: "74266",
    name: "74266 Quad 2-input XNOR",
    description: "Contains four independent 2-input XNOR gates.",
    pinout: createQuadGatePinout("XNOR"),
    datasheetUrl: "https://www.futurlec.com/Datasheet/74ls/74LS266.pdf",
    diagramUrl: "/images/xnor-gate.jpg"
  },
};
